// saple_vue_express_spa/vue/src/views/signup.vue
<!-- signup.vue -->

<template>
  <div class="signup">
    <h3>サインアップ</h3>
    <form class="form" @submit.prevent="signup">
      <div>
        <div class="user">ユーザーネーム:</div>
        <input type="text" placeholder="username" v-model="username" required />
      </div>
      <div>
        <div class="pass">パスワード:</div>
        <input
          type="password"
          placeholder="password"
          v-model="password"
          required
        />
      </div>
      <button class="signup-button">サインアップ</button>
    </form>
  </div>

</template>

<script setup lang="ts">
import { ref } from 'vue';
import { signUp } from '../auth/authService';
import { useRouter } from 'vue-router';

const router = useRouter();
const username = ref('');
const password = ref('');

const signup = async () => {
  try {
    const session = await signUp(username.value, password.value);
    console.log('Sign up successful', session);
    router.push('/confirm?email=' + username.value);
  } catch (error) {
    alert(`Sign up failed: ${error}`);
  }
};
</script>

// sample_next/src/app/auth/signup/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { signUp } from '../authService';

const SignUpPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const router = useRouter();

  const handleSignUp = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    if (password !== confirmPassword) {
      alert('Passwords do not match');
      return;
    }
    try {
      await signUp(email, password);
      router.push('/confirm?email=' + encodeURIComponent(email));
    } catch (error) {
      alert(`Sign up failed: ${error}`);
    }
  };

  return (
    <div className="loginForm">
      <h1>Welcome</h1>
      <h4>Sign up to create an account</h4>
      <form onSubmit={handleSignUp}>
        <div>
          <input
            className="inputText"
            id="email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email"
            required
          />
        </div>
        <div>
          <input
            className="inputText"
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password"
            required
          />
        </div>
        <div>
          <input
            className="inputText"
            id="confirmPassword"
            type="password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            placeholder="Confirm Password"
            required
          />
        </div>
        <button type="submit">Sign Up</button>
      </form>
      <button onClick={() => router.push('/auth/signin')}>
        Already have an account? Sign In
      </button>
    </div>
  );
};

export default SignUpPage;
