// saple_vue_express_spa/vue/src/views/signin.vue
<!-- signin.vue -->
<template>
  <div class="signin">
    <h3>サインイン</h3>
    <form class="form" @submit.prevent="signin">
      <div>
        <div class="user">ユーザーネーム:</div>
        <input type="text" placeholder="username" v-model="username" required />
      </div>
      <div>
        <div class="pass">パスワード:</div>
        <input
          type="password"
          placeholder="password"
          v-model="password"
          required
        />
      </div>
      <button class="signin-button">サインイン</button>
    </form>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { signIn } from '../auth/authService';
import { useRouter } from 'vue-router';

const router = useRouter();
const username = ref('');
const password = ref('');

const signin = async () => {
  try {
    const session = await signIn(username.value, password.value);
    console.log('Sign in successful', session);
    if (session && typeof session.AccessToken !== 'undefined') {
      sessionStorage.setItem('accessToken', session.AccessToken);
      if (sessionStorage.getItem('accessToken')) {
        router.push('/home');
      } else {
        console.error('Session token was not set properly.');
      }
    } else {
      console.error('SignIn session or AccessToken is undefined.');
    }
  } catch (error) {
    alert(`Sign in failed: ${error}`);
  }
};
</script>

// sample_next/src/app/auth/signin/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { signIn } from '../authService';

const SignInPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();

  const handleSignIn = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    try {
      const session = await signIn(email, password);
      console.log('Sign in successful', session);
      if (session && typeof session.AccessToken !== 'undefined') {
        sessionStorage.setItem('accessToken', session.AccessToken);
        if (sessionStorage.getItem('accessToken')) {
          router.push(`/home`);
        } else {
          console.error('Session token was not set properly.');
        }
      } else {
        console.error('SignIn session or AccessToken is undefined.');
      }
    } catch (error) {
      alert(`Sign in failed: ${error}`);
    }
  };

  return (
    <div className="loginForm">
      <h1>Welcome</h1>
      <h4>Sign in to your account</h4>
      <form onSubmit={handleSignIn}>
        <div>
          <input
            className="inputText"
            id="email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email"
            required
          />
        </div>
        <div>
          <input
            className="inputText"
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password"
            required
          />
        </div>
        <button type="submit">Sign In</button>
      </form>
      <button onClick={() => router.push('/auth/signup')}>
        Need an account? Sign Up
      </button>
    </div>
  );
};

export default SignInPage;
