// sample_next/src/app/auth/confirm/page.tsx
// src/app/confirm/page.tsx
'use client';

import React, { useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { confirmSignUp } from '../authService';

const ConfirmUserPage = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [email, setEmail] = useState(searchParams.get('email') || '');
  const [confirmationCode, setConfirmationCode] = useState('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      await confirmSignUp(email, confirmationCode);
      alert("Account confirmed successfully!\nSign in on next page.");
      router.push('/auth/signin');
    } catch (error) {
      alert(`Failed to confirm account: ${error}`);
    }
  };

  return (
    <div className="loginForm">
      <h2>Confirm Account</h2>
      <form onSubmit={handleSubmit}>
        <div>
          <input
            className="inputText"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email"
            required
          />
        </div>
        <div>
          <input
            className="inputText"
            type="text"
            value={confirmationCode}
            onChange={(e) => setConfirmationCode(e.target.value)}
            placeholder="Confirmation Code"
            required
          />
        </div>
        <button type="submit">Confirm Account</button>
      </form>
    </div>
  );
};

export default ConfirmUserPage;

// saple_vue_express_spa/vue/src/views/confirm.vue
<!-- confirm.vue -->

<template>
  <div class="confirm">
    <!-- メールアドレスと認証コードを突合する -->
    <h3>メールアドレスを確認してください</h3>
    <form class="form" @submit.prevent="confirm">
      <div>
        <div class="user">メールアドレス:</div>
        <input
          type="text"
          placeholder="email"
          v-model="email"
          required
          readonly
        />
      </div>
      <div>
        <div class="code">認証コード:</div>
        <input type="text" placeholder="code" v-model="code" required />
      </div>
      <button class="confirm-button">確認</button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { confirmSignUp } from '../auth/authService';
import { useRouter } from 'vue-router';

const router = useRouter();
const email = ref('');
const code = ref('');

const confirm = async () => {
  try {
    await confirmSignUp(email.value, code.value);
    router.push('/signin');
  } catch (error) {
    alert(`確認に失敗しました: ${error}`);
  }
};

onMounted(() => {
  const urlParams = new URLSearchParams(window.location.search);
  email.value = urlParams.get('email') || '';
});
</script>
